# Generated by Django 5.1.3 on 2024-11-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asicdevice',
            name='ip',
            field=models.URLField(),
        ),
    ]
