# Generated by Django 5.1.3 on 2024-11-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_asicdevice_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsicHashrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hashrate', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashrate_history', to='api.asicdevice')),
            ],
        ),
    ]
