# Generated by Django 5.1.3 on 2024-11-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_asichashrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='asicdevice',
            name='fan_count',
            field=models.IntegerField(default=0),
        ),
    ]
