# Generated by Django 5.1.3 on 2024-11-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_asicdevice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asicdevice',
            name='ip',
            field=models.CharField(max_length=200),
        ),
    ]
