# Generated by Django 5.1.3 on 2024-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_asicdevice_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asicdevice',
            name='type',
            field=models.CharField(choices=[('antminer', 'Antminer'), ('whatsminer', 'Whatsminer'), ('innosilicon', 'Innosilicon')], max_length=50),
        ),
    ]
